/**
 * review-agent.mjs
 *
 * GitHub Actions review agent.
 * Reads a git diff from stdin (or the DIFF_TEXT env var), sends it to Gemini,
 * and appends a dated entry to CODEBASE_LOG.md.
 *
 * Usage:
 *   git diff HEAD~1 HEAD | node scripts/review-agent.mjs
 *
 * Required env vars:
 *   GEMINI_API_KEY  – Google Gemini API key
 *
 * Optional env vars:
 *   COMMIT_SHA      – short SHA for the log header
 *   COMMIT_MSG      – commit message for context
 *   COMMIT_AUTHOR   – author display name
 *   LOG_FILE        – path to the log file (default: CODEBASE_LOG.md)
 */

import { GoogleGenAI } from '@google/genai';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';

// ── Config ─────────────────────────────────────────────────────────────────

const MODEL_ID = 'gemini-2.0-flash';
const LOG_FILE = resolve(process.env.LOG_FILE ?? 'CODEBASE_LOG.md');
const MAX_DIFF_CHARS = 20_000; // truncate very large diffs to stay within token limits

// ── Read diff from stdin ────────────────────────────────────────────────────

function readStdin() {
  try {
    return readFileSync('/dev/stdin', 'utf8');
  } catch {
    return '';
  }
}

const rawDiff = (process.env.DIFF_TEXT || readStdin()).trim();

if (!rawDiff) {
  console.error('No diff provided – nothing to review.');
  process.exit(0);
}

const diff =
  rawDiff.length > MAX_DIFF_CHARS
    ? rawDiff.slice(0, MAX_DIFF_CHARS) + '\n... (diff truncated)'
    : rawDiff;

// ── Gemini review ───────────────────────────────────────────────────────────

const apiKey = process.env.GEMINI_API_KEY;
if (!apiKey) {
  console.error('GEMINI_API_KEY environment variable is not set.');
  process.exit(1);
}

const ai = new GoogleGenAI({ apiKey });

const commitSha = process.env.COMMIT_SHA ?? 'unknown';
const commitMsg = process.env.COMMIT_MSG ?? '';
const commitAuthor = process.env.COMMIT_AUTHOR ?? '';

const prompt = `You are a senior software engineer reviewing a git commit for a local AI desktop application built with React, TypeScript, Electron and the Google Gemini SDK.

Commit: ${commitSha}${commitMsg ? `\nMessage: ${commitMsg}` : ''}${commitAuthor ? `\nAuthor: ${commitAuthor}` : ''}

Diff:
\`\`\`diff
${diff}
\`\`\`

Write a concise technical summary (3-8 bullet points) of what this commit does. Focus on:
- What files/modules were changed and why
- Any new features, bug fixes, or refactors introduced
- Important design decisions or patterns used
- Anything future developers should know when working with these areas

Keep the summary factual and to the point. Do not include a greeting or closing.`;

console.log(`Sending diff to Gemini (${MODEL_ID})…`);

let summary;
try {
  const response = await ai.models.generateContent({
    model: MODEL_ID,
    contents: [{ role: 'user', parts: [{ text: prompt }] }],
    config: { temperature: 0.2 },
  });
  summary = response.text?.trim() ?? '(no summary returned)';
} catch (err) {
  console.error('Gemini request failed:', err.message);
  process.exit(1);
}

// ── Append to CODEBASE_LOG.md ───────────────────────────────────────────────

const timestamp = new Date().toISOString().replace('T', ' ').slice(0, 19) + ' UTC';

const entry = `\n---\n\n## ${timestamp} — \`${commitSha}\`${commitMsg ? `\n> ${commitMsg}` : ''}\n\n${summary}\n`;

let existing = '';
if (existsSync(LOG_FILE)) {
  existing = readFileSync(LOG_FILE, 'utf8');
} else {
  existing =
    '# Codebase Change Log\n\nThis file is auto-generated by the code-review-agent workflow.\nEach entry summarises a commit pushed to the repository.\n';
}

writeFileSync(LOG_FILE, existing + entry, 'utf8');

console.log(`Log entry appended to ${LOG_FILE}`);
console.log('\n--- Summary ---\n');
console.log(summary);
